In [1]:
import numpy as np

In [2]:
x =[[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [3]:
ar = np.array(x)

In [4]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [5]:
ar.sum(axis=0)

array([12,  8,  9])

In [6]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [7]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [8]:
ar.flat

In [9]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [10]:
ar.ndim

2

In [11]:
ar.size

9

In [12]:
ar.nbytes

36

In [13]:
one = np.array([1,3,4,634,2])

In [14]:
one.argmax()

3

In [15]:
one.argmin()

0

In [16]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [17]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [18]:
ar.argmax()

6

In [19]:
ar.argmin()

8

In [20]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [21]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [22]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [23]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [33]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [35]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [36]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [37]:
[547, 6754] + [623, 9832]

[547, 6754, 623, 9832]

In [38]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [39]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [40]:
ar.sum()

29

In [42]:
ar.max()

7

In [44]:
ar.min()

0

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [47]:
type(np.where(ar>5))

tuple

In [48]:
np.count_nonzero(ar)

8

In [49]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [51]:
ar[1,2] = 0

In [52]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [53]:
import sys

In [54]:
py_ar = [0,4,55,2]

In [55]:
np_ar = np.array(py_ar)

In [57]:
sys.getsizeof(1)

28

In [58]:
len(py_ar)

4

In [59]:
sys.getsizeof(1) * len(py_ar)

112

In [60]:
np_ar.itemsize * np_ar.size

16