In [1]:
import numpy as np


In [2]:
# create an array
m_list = [1,5,6,95,45]

In [3]:
np.array(m_list)

array([ 1,  5,  6, 95, 45])

In [4]:
array__ = np.array(m_list)

In [5]:
array__

array([ 1,  5,  6, 95, 45])

In [6]:
m_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
metrix__ = np.array(m_matrix)

In [8]:
metrix__

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
m_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [12]:
arr = np.arange(0,11,3)

In [13]:
arr.shape

(4,)

In [14]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.zeros(5, order = 'F')

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,15,5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [21]:
np.random.rand(5)

array([0.02085616, 0.15148696, 0.17294807, 0.68960021, 0.84066352])

In [22]:
np.random.rand(3,2)

array([[8.33962901e-01, 6.28778419e-01],
       [3.75030435e-01, 1.79358337e-04],
       [6.01045158e-02, 4.42453504e-01]])

In [23]:
np.random.randint(2,7)

5

In [24]:
np.random.randint(2,7,100)

array([6, 3, 3, 4, 6, 5, 2, 5, 3, 6, 4, 2, 3, 5, 5, 5, 6, 2, 6, 5, 5, 4,
       5, 3, 3, 5, 4, 4, 3, 2, 5, 4, 6, 4, 3, 4, 6, 3, 2, 6, 4, 2, 3, 3,
       6, 2, 6, 3, 5, 3, 2, 4, 5, 3, 6, 4, 3, 4, 2, 3, 3, 6, 2, 4, 3, 2,
       2, 5, 3, 2, 5, 6, 2, 2, 3, 3, 4, 2, 2, 3, 3, 6, 4, 6, 4, 2, 4, 6,
       4, 6, 4, 3, 3, 6, 3, 4, 2, 4, 3, 5])

In [25]:
rrrr = np.random.randint(2,60,100)

In [26]:
rrrr.shape

(100,)

In [27]:
rrrr

array([47, 19, 28, 57, 41,  2, 49, 41, 37,  9, 29, 59, 40,  8, 17, 54, 20,
       53, 32, 35,  3, 34, 46, 35, 41, 32,  4, 44, 24, 23, 48, 48, 12, 49,
       27, 44, 24, 59, 20, 32,  5, 53, 44, 38, 10,  4, 58, 18, 26, 45,  8,
       25, 32, 59, 28, 30, 39, 22, 21,  5, 41, 52, 33, 33, 27,  9, 10, 42,
        2, 20, 13, 32, 10, 49, 17, 53, 16, 12, 36, 47, 25, 11, 42, 32, 34,
       26, 39, 56,  6, 34,  3, 39, 27, 42, 13, 35, 22, 29, 21, 32])

In [28]:
    RRR = rrrr.reshape(20,5)

In [29]:
RRR

array([[47, 19, 28, 57, 41],
       [ 2, 49, 41, 37,  9],
       [29, 59, 40,  8, 17],
       [54, 20, 53, 32, 35],
       [ 3, 34, 46, 35, 41],
       [32,  4, 44, 24, 23],
       [48, 48, 12, 49, 27],
       [44, 24, 59, 20, 32],
       [ 5, 53, 44, 38, 10],
       [ 4, 58, 18, 26, 45],
       [ 8, 25, 32, 59, 28],
       [30, 39, 22, 21,  5],
       [41, 52, 33, 33, 27],
       [ 9, 10, 42,  2, 20],
       [13, 32, 10, 49, 17],
       [53, 16, 12, 36, 47],
       [25, 11, 42, 32, 34],
       [26, 39, 56,  6, 34],
       [ 3, 39, 27, 42, 13],
       [35, 22, 29, 21, 32]])

In [30]:
RRR.max()

59

In [31]:
RRR.min()

2

In [32]:
RRR.argmax()

11

In [33]:
RRR.argmin()

5

# Numpy Indexing and Selection

In [34]:
rrrr

array([47, 19, 28, 57, 41,  2, 49, 41, 37,  9, 29, 59, 40,  8, 17, 54, 20,
       53, 32, 35,  3, 34, 46, 35, 41, 32,  4, 44, 24, 23, 48, 48, 12, 49,
       27, 44, 24, 59, 20, 32,  5, 53, 44, 38, 10,  4, 58, 18, 26, 45,  8,
       25, 32, 59, 28, 30, 39, 22, 21,  5, 41, 52, 33, 33, 27,  9, 10, 42,
        2, 20, 13, 32, 10, 49, 17, 53, 16, 12, 36, 47, 25, 11, 42, 32, 34,
       26, 39, 56,  6, 34,  3, 39, 27, 42, 13, 35, 22, 29, 21, 32])

In [35]:
rrrr[3]

57

In [36]:
rrrr[5:17]

array([ 2, 49, 41, 37,  9, 29, 59, 40,  8, 17, 54, 20])

# broadcasting

In [37]:
rrrr

array([47, 19, 28, 57, 41,  2, 49, 41, 37,  9, 29, 59, 40,  8, 17, 54, 20,
       53, 32, 35,  3, 34, 46, 35, 41, 32,  4, 44, 24, 23, 48, 48, 12, 49,
       27, 44, 24, 59, 20, 32,  5, 53, 44, 38, 10,  4, 58, 18, 26, 45,  8,
       25, 32, 59, 28, 30, 39, 22, 21,  5, 41, 52, 33, 33, 27,  9, 10, 42,
        2, 20, 13, 32, 10, 49, 17, 53, 16, 12, 36, 47, 25, 11, 42, 32, 34,
       26, 39, 56,  6, 34,  3, 39, 27, 42, 13, 35, 22, 29, 21, 32])

In [38]:
rrrr[5:60] = 555
rrrr

array([ 47,  19,  28,  57,  41, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555,  41,  52,  33,  33,  27,
         9,  10,  42,   2,  20,  13,  32,  10,  49,  17,  53,  16,  12,
        36,  47,  25,  11,  42,  32,  34,  26,  39,  56,   6,  34,   3,
        39,  27,  42,  13,  35,  22,  29,  21,  32])

In [39]:
array_2d = np.array([[21,34,5],[75,2,45],[1,375,4]])

In [40]:
array_2d

array([[ 21,  34,   5],
       [ 75,   2,  45],
       [  1, 375,   4]])

In [41]:
array_2d[2]

array([  1, 375,   4])

In [42]:
array_2d[2][1]

375

In [43]:
array_2d[0:2,2]

array([ 5, 45])

In [44]:
array_2d[1,1:2]

array([2])

In [45]:
array_2d[0:2,1:]

array([[34,  5],
       [ 2, 45]])

In [46]:
array_2d_2_ = np.zeros((10,10))
array_2d_2_

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
for i in range(len(array_2d_2_)):
    array_2d_2_[i] = i+1

In [48]:
array_2d_2_

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [49]:
array_2d_2_[[ 4,  2,   5, 8, ]]

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [50]:
rrrr

array([ 47,  19,  28,  57,  41, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555,  41,  52,  33,  33,  27,
         9,  10,  42,   2,  20,  13,  32,  10,  49,  17,  53,  16,  12,
        36,  47,  25,  11,  42,  32,  34,  26,  39,  56,   6,  34,   3,
        39,  27,  42,  13,  35,  22,  29,  21,  32])

In [51]:
rrrr > 25

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True, False, False, False,  True,
       False,  True, False,  True, False, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
        True])

In [52]:
rrrr < 20

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
        True, False,  True, False,  True,  True, False, False, False,
        True, False, False, False, False, False, False,  True, False,
        True, False, False, False,  True, False, False, False, False,
       False])

In [53]:
rrrr[rrrr > 25]

array([ 47,  28,  57,  41, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555,  41,  52,  33,  33,  27,  42,
        32,  49,  53,  36,  47,  42,  32,  34,  26,  39,  56,  34,  39,
        27,  42,  35,  29,  32])

In [54]:
rrrr[rrrr < 20]

array([19,  9, 10,  2, 13, 10, 17, 16, 12, 11,  6,  3, 13])

In [55]:
rrrr.any() < 20

True

In [56]:
rrrr.any() > 0

True

In [57]:
rrrr.any() > 2

False

In [58]:
rrrr.any() < 0

False

In [59]:
rrrr.all() < 100

True

In [60]:
complex(6-2j)

(6-2j)

In [61]:
aarrrr = np.arange(5,13, dtype=complex)

aarrrr

array([ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j,
       12.+0.j])

# More Functions

In [62]:
rrrr

array([ 47,  19,  28,  57,  41, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555,
       555, 555, 555, 555, 555, 555, 555, 555,  41,  52,  33,  33,  27,
         9,  10,  42,   2,  20,  13,  32,  10,  49,  17,  53,  16,  12,
        36,  47,  25,  11,  42,  32,  34,  26,  39,  56,   6,  34,   3,
        39,  27,  42,  13,  35,  22,  29,  21,  32])

In [63]:
array_2d_2_

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [64]:
rrrr.ndim

1

In [65]:
array_2d_2_.ndim

2

In [66]:
x  = np.array([[56,3,4],[6,6,4],[4,567,8]])

In [67]:
x

array([[ 56,   3,   4],
       [  6,   6,   4],
       [  4, 567,   8]])

In [68]:
np.std(x)

175.34438776586967

In [69]:
print(f"Std of rows {np.std(x, axis=0)}")
print(f"Std of column {np.std(x, axis=1)}")

Std of rows [ 24.0554914  265.16787136   1.88561808]
Std of column [ 24.75210429   0.94280904 264.46297788]


In [70]:
np.diag((3,4,2,5,6,7))

array([[3, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 7]])

In [71]:
np.sum(x)

658

In [72]:
np.sum(x, axis=0)

array([ 66, 576,  16])

In [73]:
np.sum(x, axis=1)

array([ 63,  16, 579])

In [74]:
p = np.array([23,56,78,43,2365,813,57665,46,82,51,48,94,341,934])

In [75]:
np.random.choice(p,6)

array([341,  48,  56,  23, 341,  82])

In [122]:
n = np.random.choice(['t',7,2,'a','d','f',5,3,1], 15)

In [123]:
n

array(['5', 'd', 'd', 't', '3', '1', '7', '7', 'd', '3', 't', '2', '5',
       '7', '7'], dtype='<U1')

# Harry....

In [78]:
ide = np.identity(9)

In [79]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
Arr = np.arange(99)
Arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [81]:
arrr = Arr.reshape(3,33)
arrr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [82]:
abc = arrr.ravel()

In [83]:
abc.shape

(99,)